package com.jiuyi.ndr.dao.subject.sql;

import com.jiuyi.ndr.domain.subject.Subject;
import org.apache.ibatis.jdbc.SQL;
import org.springframework.util.StringUtils;

/**
 * @author ke 2017/6/15
 */
public class SubjectDaoSql {

    public String updateSql(final Subject subject){
        return new SQL(){
            {
                UPDATE("ndr_subject");
                if(!StringUtils.isEmpty(subject.getSubjectId())){
                    SET("subject_id=#{subjectId}");
                }
                if(!StringUtils.isEmpty(subject.getName())){
                    SET("name=#{name}");
                }
                if(!StringUtils.isEmpty(subject.getBorrowerId())){
                    SET("borrower_id=#{borrowerId}");
                }
                if(!StringUtils.isEmpty(subject.getBorrowerIdXM())){
                    SET("borrower_id_xm=#{borrowerIdXM}");
                }
                if(!StringUtils.isEmpty(subject.getIntermediatorId())){
                    SET("intermediator_id=#{intermediatorId}");
                }
                if(!StringUtils.isEmpty(subject.getIntermediatorIdXM())){
                    SET("intermediator_id_xm=#{intermediatorIdXM}");
                }
                if(!StringUtils.isEmpty(subject.getType())){
                    SET("type=#{type}");
                }
                if(subject.getTerm()!=null){
                    SET("term=#{term}");
                }
                if(subject.getPeriod()!=null){
                    SET("period=#{period}");
                }
                if(subject.getRate()!=null){
                    SET("rate=#{rate}");
                }
                if(subject.getOverduePenalty()!=null){
                    SET("overdue_penalty=#{overduePenalty}");
                }
                if(subject.getAdvancedPayoffPenalty()!=null){
                    SET("advanced_payoff_penalty=#{advancedPayoffPenalty}");
                }
                if(subject.getTotalAmt()!=null){
                    SET("total_amt=#{totalAmt}");
                }
                if(subject.getFeeAmt()!=null){
                    SET("fee_amt=#{feeAmt}");
                }
                if(!StringUtils.isEmpty(subject.getRepayType())){
                    SET("repay_type=#{repayType}");
                }
                if(subject.getInvestParam()!=null){
                    SET("invest_param=#{investParam}");
                }
                if(subject.getRaiseStatus()!=null){
                    SET("raise_status=#{raiseStatus}");
                }
                if(!StringUtils.isEmpty(subject.getRepayStatus())){
                    SET("repay_status=#{repayStatus}");
                }
                if(subject.getPushStatus()!=null){
                    SET("push_status=#{pushStatus}");
                }
                if(!StringUtils.isEmpty(subject.getPublishTime())){
                    SET("publish_time=#{publishTime}");
                }
                if(!StringUtils.isEmpty(subject.getOpenTime())){
                    SET("open_time=#{openTime}");
                }
                if(!StringUtils.isEmpty(subject.getCloseTime())){
                    SET("close_time=#{closeTime}");
                }
                if(!StringUtils.isEmpty(subject.getLendTime())){
                    SET("lend_time=#{lendTime}");
                }
                if(subject.getOpenFlag()!=null){
                    SET("open_flag=#{openFlag}");
                }
                if(subject.getOpenChannel()!=null){
                    SET("open_channel=#{openChannel}");
                }
                if(subject.getAvailableAmt()!=null){
                    SET("available_amt=#{availableAmt}");
                }
                if(subject.getCurrentTerm()!=null){
                    SET("current_term=#{currentTerm}");
                }
                if(subject.getPaidPrincipal()!=null){
                    SET("paid_principal=#{paidPrincipal}");
                }
                if(subject.getPaidInterest()!=null){
                    SET("paid_interest=#{paidInterest}");
                }
                if(!StringUtils.isEmpty(subject.getExtSn())){
                    SET("ext_sn=#{extSn}");
                }
                if(subject.getExtStatus()!=null){
                    SET("ext_status=#{extStatus}");
                }
                if(subject.getDirectFlag()!=null){
                    SET("direct_flag=#{directFlag}");
                }
                if(!StringUtils.isEmpty(subject.getContractNo())){
                    SET("contract_no=#{contractNo}");
                }
                if(subject.getAssetsSource()!=null){
                    SET("assets_source=#{assetsSource}");
                }
                if(!StringUtils.isEmpty(subject.getOperator())){
                    SET("operator=#{operator}");
                }
                if(subject.getAccountingDepartment()!=null){
                    SET("accounting_department=#{accountingDepartment}");
                }
                if(subject.getMiscellaneousAmt()!=null){
                    SET("miscellaneous_amt=#{miscellaneousAmt}");
                }
                if(!StringUtils.isEmpty(subject.getApplyCreditAppNo())){
                    SET("apply_credit_app_no=#{applyCreditAppNo}");
                }
                if(!StringUtils.isEmpty(subject.getCompensationAccount())){
                    SET("compensation_account=#{compensationAccount}");
                }
                if(!StringUtils.isEmpty(subject.getProfitAccount())){
                    SET("profit_account=#{profitAccount}");
                }
                if(!StringUtils.isEmpty(subject.getReloanSubjectId())){
                    SET("reloan_subject_id=#{reloanSubjectId}");
                }
                if(subject.getWithdrawStatus()!=null){
                    SET("withdraw_status=#{withdrawStatus}");
                }
                if(!StringUtils.isEmpty(subject.getWithdrawSn())){
                    SET("withdraw_sn=#{withdrawSn}");
                }
                if(subject.getProfitAmt()!=null){
                    SET("profit_amt=#{profitAmt}");
                }
                if(subject.getReloanProfitAmt()!=null){
                    SET("reloan_profit_amt=#{reloanProfitAmt}");
                }
                if(subject.getInvestRate()!=null){
                    SET("invest_rate=#{investRate}");
                }
                if(!StringUtils.isEmpty(subject.getTransferParamCode())){
                    SET("transfer_param_code=#{transferParamCode}");
                }
                if(subject.getActivityId()!=null){
                    SET("activity_id=#{activityId}");
                }
                if(subject.getBonusRate()!=null){
                    SET("bonus_rate=#{bonusRate}");
                }
                if(subject.getNewbieOnly()!=null){
                    SET("newbie_only=#{newbieOnly}");
                }
                if(subject.getIsVisiable()!=null){
                    SET("is_visiable=#{isVisiable}");
                }
                if(subject.getAutoInvestQuota()!=null){
                    SET("auto_invest_quota=#{autoInvestQuota}");
                }
                if(!StringUtils.isEmpty(subject.getRepayTime())){
                    SET("repay_time=#{repayTime}");
                }
                if(subject.getSortNum()!=null){
                    SET("sort_num=#{sortNum}");
                }
                WHERE("id=#{id}");
            }
        }.toString();
    }
}
