spring:
  type: com.alibaba.druid.pool.DruidDataSource
  datasourceRW:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.42.171.28:3306/cunguan02?characterEncoding=utf-8&allowMultiQueries=true
    username: cunguan_investrw
    password: ENC(aDdQenmlI7fZjASwM7VsSL0FPH6+MSLW)
    max-active: 50
    initial-size: 10
    max-wait: 60000
    max-idle: 20
    min-idle: 10
    validation-query: select 1 #validationQuery是检查时用的sql语句
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    time-between-eviction-runs-millis: 60000 #隔多少时间回收废弃连接   一般比minEvictableIdleTimeMillis小
    min-evictable-idle-time-millis: 300000
  datasourceR:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://121.42.171.28:3306/cunguan02?characterEncoding=utf-8&allowMultiQueries=true
      username: cunguan_investr
      password: ENC(F7Ei7M3M/pvX2ii071bPbAbv3Rcd0ylB)
      max-active: 50
      initial-size: 10
      max-wait: 60000
      max-idle: 20
      min-idle: 10
      validation-query: select 1 #validationQuery是检查时用的sql语句
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      time-between-eviction-runs-millis: 60000 #隔多少时间回收废弃连接   一般比minEvictableIdleTimeMillis小
      min-evictable-idle-time-millis: 300000


server:
  port: 8083

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    use-generated-keys: true

management:
  security:
    enabled: false

xm:
  enviroment:
    url: "https://p2pcunguan.xmbankonline.com/bha-neo-app/lanmaotech/"
    platformNo: "3000000203"
    publicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkDKZEX0em+MRRP4POWTD5Rfkb7oHLwFZHwRiPWkP4BDhJyof0SUkk0zpY0JAHH33589VQCxnS6uZfw5gzPVdYgZyBPxJcEERERKHUNcOQFbpJEf363BobkJtl28PWTvb4NMXVOnwPzyhl4dr7wtgnwXd22rYBOKjD+QSIouQGwEGutAHFrCmSdMDePLLdAMHHF9OlredX3Pp0qcukQ0G/IoDZ3YMDwVqx/xuLadD7irYVS8Dw9f3lde2AS5YSoMbvSxfzZjOiqX2Wnnz6Me5rlouh3qXtYd943cap+ck8R1is7BJz8B7ipCeVHUl7qjHC7UeQRc1tnatihrjjxZ5OwIDAQAB"
    privateKey: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDAsENj+hdmOaAVC5fOBbFG2rkKnMmMfV7DKO/dg2nFgvU3NI40baUdKe+V3YKPXZ4rD24hBKhPgRcqrihKg2415cWsrigizasHWvrcg/+tMJiEhWfUlcEurlZM97x2CL4hmGNFYti1zUfXDpt6jHdu+Q+arZrG+UbFLXIEtARwkU5Ja+3Jdga3pf642cOAWrhKy/dkW9A8bmzTLIGbtaYfh19XV+fkaUdyjKVJDPF2HhwdrCYvwH5cArLjIQZh7CMmc9kIENw1EqMkwYS9VxuIwL1djp7W1vrypvdkQ0UCyRE4blhUMXzRseHVm3plKh9NqEmWGmczF9/R4RKsfUeZAgMBAAECggEAUrQU6LdyDaVUKVRFft8AnPnKDF0JQOyanMdYVMpPvr+bwmsjUitxgBf8xmVB4Yj8F11TFobqOt2cdOw1TO4mgqmxc5F4lp+R9eE95SIevlYqUE72Js90EDYxwm1ejYbpHIBMs35ep4GJgSu63hmmNZJe+TPkR9y8XGtKEey2Lx3fsF5mJjnPb6YkgSLP2bg43W5wGH9EZSqEqUpyvh5DIhD5iIHaEUdgEO0LnUz/FGUF8Du3RKfs0KRxPZTP5QPeXkEU19ivOM66qsSMXIYfewIRIBThI32+Mpzn2f6OJKZuz5u2n+i6NGqv5WIAVZ2leaHSzun/68WX+yjCYOrhgQKBgQDwIC7S8mJsuuOymDcExfsogsGGNL/b9HDkJgnXdVi5ibr0QhD6MC/dfxZeEchh7H7GsFJspK33ZXGJjx/+MvGJhZtd2L15b+s0C6/qa6ZKNJk5Oi9I7fG4yqW9vgM2bupQvROsWHJ4ZJ1PCvoofgsb4MoIn2gVGBKi01+XqT11cQKBgQDNbURve3CPvEq1tG6RzQ6MiRiUhoUOqS4SGiCLOEFflNwxn+PJcdjgj4hm/kEJAQ2NUEkHc/H1tQm7SeIhRr5bimhiWV4BiAYHfQpdzBpVdG4sr54e8iSmMxRliPWxJ5v+DJv8r0uP14aa7VePOnVhXyHVT6juGPfTY6WR5TbAqQKBgD7/kolRgjUYiyiN+tFLx+sG8xLsv/FLHlsdB7P5W3/B/MScmKuq/MPV1d50N+hJDbG/DMDoK6Qefz0hybj9UJVN8kca2AsGK+UJs+uCtqv9RL3Y4BL4KlTbBcTUFy+uxdbM5F5xDgc8DnFwZdU9zFhSD29Xswzlte32GrxFcJRhAoGBAJEAs/HNPCL5UfL4raOVDtP8YbFVUs6KdM6qSpZ62wpQ1SziI7Op/OBl8G5iwh1M9Pfu192+5ef+JiRhfpDmkq+i/xOM6WJDVZ4rkQmsbFotmSdJv18wpNX78EXLa0HlJ6Mn22N9iOS7yXPKXKfpJ7nXoNYlKKUIUsaP6+sT1JYhAoGBAM6Dqe0G/v10JxEF0Z6cpx8ftnp2iDxEFm7v3b6ObxHvVSNlJC6v34E8VuT6o1ylAjwoogWnPqkUnlTtD3+ag5XS8RiEsVwbotyQXi8gfbQ8aB7iE0P+up3TA06Hec6bS3v/ik4X9YS6PckPHK7ju5fUsEPBT8pQ9DNhTbjyIluH"
  response :
    baffle: 0 #交易挡板 挡板开关 1开启、0关闭
    time: 1 #时间挡板 挡板开关 1开启、0关闭

notice:
  url: http://dev01-soa-notify.duanrong.com
  key: duanrongf0f22ac60d07407cfb7c587f9cab
  source: iplan-service
  version: 1.0.0

drpay:
  url: http://cunguan01-soa-drpay.duanrong.com
  key: duanrongf0f22ac60d07407cfb7c587f9cab
  source: iplan-service
  version: 1.0.0

iPlan:
  oss:
    imagePrefix: https://duanrongweb.oss-cn-qingdao.aliyuncs.com #正式地址
  invest:
    investUserUrl: http://cunguan01-m.duanrong.com/iplan/talent #投资达人链接
    questionUrl: http://cunguan01-m.duanrong.com/html/app/lcjhQue.html  #问题链接
    shareLinkUrl: http://cunguan01-m.duanrong.com/iplanDetail/  #分享链接

FDD: #法大大生产配置
  FDD_APP_ID: "000191"
  FDD_SECRET: TEYetxF59TaRkIx8A56GQedi
  FDD_VERSION: "2.0"
  FDD_URL: https://extapi.fadada.com/api2/

duanrong:
  redis:
    host: 118.190.70.42
    password: duanrong123456!@#
    port: 6379
    timeout: 30000
    prefix: cunguan01
    config:
      maxIdle: 10
      maxTotal: 100
      minIdle: 4
      maxWaitMillis: 60000
  invest:
      shareLinkUrl: https://cunguan01-marketing-m.duanrong.com/weighting/profit/registe1
      tyjUrl: https://cunguan01-marketing-m.duanrong.com/weighting/profit/index.htm?userId=
      successUrl: http://cunguan01-soa-marketing.duanrong.com/web/invest/getInvestSuccess.do
  subject:
      detailUrl: https://cunguan01-m.duanrong.com/app/iplanDetail/borrowerInfo         #散标详情页项目详情
      fengkongUrl:  https://cunguan01-m.duanrong.com/newloan/fengkong     #风控信息
      investUrl:   https://cunguan01-m.duanrong.com/newloan/subjectTalent       #投资达人
      shareLinkUrl: https://cunguan01-m.duanrong.com/newloan/detail/      #投资完分享链接
      protocolUrl: http://duanrongweb.oss-cn-qingdao.aliyuncs.com/file/%E5%80%9F%E6%AC%BE%E5%8F%8A%E5%B1%85%E9%97%B4%E6%9C%8D%E5%8A%A1%E5%8D%8F%E8%AE%AE.pdf       #散标投资协议
      riskProtocolUrl: https://cunguan01-m.duanrong.com/html/riskInformed.html   #风险协议
      transferUrl: http://duanrongweb.oss-cn-qingdao.aliyuncs.com/file/%E5%80%BA%E6%9D%83%E8%BD%AC%E8%AE%A9%E5%8F%8A%E5%B1%85%E9%97%B4%E6%9C%8D%E5%8A%A1%E5%8D%8F%E8%AE%AE.pdf   #转让协议
      transferExplainUrl: https://cunguan01-m.duanrong.com/html/app/transfer.html   #转让说明
      purchaseRecordUrl: https://cunguan01-m.duanrong.com/zqzr/transLog    #债转详情页加入记录
      creditDetailUrl: https://cunguan01-m.duanrong.com/app/iplan/borrowerInfo    #债权明细
  credit:
    creditIntroduceUrl: http://m.duanrong.com