spring:
  type: com.alibaba.druid.pool.DruidDataSource
  datasourceRW:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rdsk2rxa7o8hr2tp7s4ab.mysql.rds.aliyuncs.com:3306/jiuyicaifu?characterEncoding=utf-8&allowMultiQueries=true
    username: rootadmin
    password: ENC(6QsI4y1CFu54OFuRqxsdPEgg6maPwELz)
    max-active: 50
    initial-size: 10
    max-wait: 60000
    max-idle: 20
    min-idle: 10
 #   validation-query: select 1 #validationQuery是检查时用的sql语句
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    time-between-eviction-runs-millis: 60000 #隔多少时间回收废弃连接   一般比minEvictableIdleTimeMillis小
    min-evictable-idle-time-millis: 300000
    removeAbandoned: true #是否自动回收超时连接
    removeAbandonedTimeout: 180 #回收时间
  datasourceR:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.157.104.10:3306/jiuyicaifu?characterEncoding=utf-8
    username: rootadmin
    password: ENC(6QsI4y1CFu54OFuRqxsdPEgg6maPwELz)
    max-active: 50
    initial-size: 10
    max-wait: 60000
    max-idle: 20
    min-idle: 10
 #  validation-query: select 1 #validationQuery是检查时用的sql语句
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    time-between-eviction-runs-millis: 60000 #隔多少时间回收废弃连接   一般比minEvictableIdleTimeMillis小
    min-evictable-idle-time-millis: 300000
    removeAbandoned: true #是否自动回收超时连接
    removeAbandonedTimeout: 180 #回收时间


server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    use-generated-keys: true

management:
  security:
    enabled: false

xm:
  enviroment:
    url: https://cunguan.xmbankonline.com/bha-neo-app/lanmaotech/
    platformNo: 3000000139
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkKD2qQwKHCoVww0Z+w9bSds0+PuytE+TJECkvmCvmv75fjPrCMduOsiY0yiVP0BUPTb0s+qIg+rh951RO71QHseIPrHhAmLwrNU32K8NC8qpW/Lmm7WmJMp4SG+CDdH1XccWWPdlvJffo3oDEhMvj3MnXtFBk3umswIdX4JOj8wGhk9xQWb0KCs6UmGWt5xORrKX/d/t5nT/zx0fAljqG4VNgfYrtY9YzRNd1AvjMjUIcGbUkSOaeFTPQBVnWbdsBUFAFsNuOFM3b/4isxl0poBsxur5kEohMmZqrZcEcV8x1WA9rxoBWsaiN9mbIDHJvzyUhpiS4UksAovnatvZSwIDAQAB
    privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQR2WBk4YLvJhDWxATrsj4Njh7XqUIBeNlBTF6fLqBHjoL9rboYx4p3UrjSI6j6vdoW4H4tkcYon6BdJmLrxHmDDdlxondWgg5lluiXOyMsZe9Og5SV3H7z5uITL5zmQQXyDTn2HYzNRSjNGe1pMxYvDwW+/pRo8teFdhIJrR8LnVtErv0B4zgIkk6h4uGPxmZy82E2bCkdlb1Lk+L6KAZSK2HvD3CyyoA9P0bMdOsHR1OC2cRnrG33u43ktTXccmQdaxQvqiRocuItPiwUDEdbKQzzCAG3wEsWqtDM3Ix0+qeZ7Kk1oSxEp3t2+48z3ij9nitUqo0ltoAIBTLa7GbAgMBAAECggEAWTKqeyLV3oLnZrlCGlvZf8ugxt0SqmvzJdlihkWSjieGzobbcIy6Z015e/sf8312dX/zGrPdoOQ+b2yjMZpJfQ8wTmsHsf+T1C3bkp5fRCXuiUCqz4LZsvEHeAj9633VreW1GrGudWG/M+IGpFkulrYOuf0yB/Kw7ttGJChHVYK9SAUTlq+16LkWkWSsTbnZir931A9CGujLXNNU+D9DT/43n2WO5zf2DZ6FRu4qGUNx0H+j2n1FeqrdeYInhnbH3nhQXzNwbcE4NlQWpiAS2ioFrVfV1eHSu3oZCjq50uFLDXkQYgkIVzTWd/0ks+o+JB+6rj4Tb8MPCQJz3yTxOQKBgQD/YOwn6SfJ7nre/4tC2NsEieKBxtn4FRgGJ6i3FWXMXcbIM1mma7Tk/c98WVBpPATcfJaGBqC4d8vo5U5OizPvI9EziZkB3m7aOmLoWQA2Sk6DuwNSRUIYMyGKY/KCAPXpP/URpyA9q5BPDg/GFda5KxAtqOAWiQp6cVpXUej4lwKBgQDQySKdPRd8ToY64PVteh7HOhiS9FKvMPLLX+0jrltkShLLyP7w8ChKTmrJigBFnxl+MbKSDbotYvyJQPDrwSlM7XKwzcCe8gJ28TqDdvuxSeuWsf72eaRY4schCIT0CyaSqPTXj7C6eS4pEbFtCKK3xVEXzZPhclYyOb3g/uFLnQKBgHvhWU1W9b0n2SS5k6Veqoe+F0la27tTCC9cJ6SAVbxYNShCeJeZIcv/Lxoj/TS/L6CBM0daibZSLnEQYvcI4a18k2vLsJROgTmNHxOUsNylGQcfvdG31QMGMpv+NdJIgwGdy9S/XI1t3vfqW058o4d5U0TC6ckkuxeASxGWo0uLAoGAK6oE7TF7memqNOIbMdwaV7wUq5chO7ZW8KWNKKssPdsn9yp/9s+i/XdM6f1MdUMCx9uI5var+xX6jpHgUM3C323BUKyXHiaq0Uk93YSiur8k4A01r0JdVqGG16e6dndmh8GCAxrv8O+q8bfbjVwC+7/uZ7X8uWd6E2L0DPwBDhkCgYEArfWr17vKE7YnE9OIeDxL1jBzALFNSfuljmM88WGeCkmxnYybN9yvWQqY6gV4lp2Pg8IuAhPJ0pkK3oucqAgo4DRZxPbwxNSiyJPtXv0Lg2t5rpRyI/ABuTpeWWIzDRUG3xETvIRmuOhHQJGhNWvSHs2n+nSy4jZVKcyl+a97bGo=
  response :
    baffle: 0 #交易挡板 挡板开关 1开启、0关闭
    time: 0 #时间挡板 挡板开关 1开启、0关闭

notice:
  url: http://soa-notify.duanrong.com
  key: duanrongf0f22ac60d07407cfb7c587f9cab
  source: iplan-service
  version: 1.0.0

drpay:
  url: http://soa-drpay.duanrong.com
  key: duanrongf0f22ac60d07407cfb7c587f9cab
  source: iplan-service
  version: 1.0.0

jasypt:
  encryptor:
    password: duanrong123

iPlan:
  oss:
    imagePrefix: https://duanrongweb.oss-cn-qingdao.aliyuncs.com #正式地址
  invest:
    investUserUrl: http://m.duanrong.com/iplan/talent #投资达人链接
    questionUrl: http://m.duanrong.com/html/app/lcjhQue.html  #问题链接
    shareLinkUrl: http://m.duanrong.com/iplanDetail/  #分享链接

FDD: #法大大生产配置
  FDD_APP_ID: "000191"
  FDD_SECRET: TEYetxF59TaRkIx8A56GQedi
  FDD_VERSION: "2.0"
  FDD_URL: https://extapi.fadada.com/api2/

duanrong:
  redis:
    host: 07b96cc9782046f9.redis.rds.aliyuncs.com
    password: TdqmcaR3NZ
    port: 6379
    timeout: 30000
    prefix: PRD
    config:
      maxIdle: 10
      maxTotal: 100
      minIdle: 4
      maxWaitMillis: 60000
  invest:
      shareLinkUrl: https://marketing-m.duanrong.com/weighting/profit/registe1
      tyjUrl: https://marketing-m.duanrong.com/weighting/profit/index.htm?userId=
      successUrl: http://soa-marketing.duanrong.com/web/invest/getInvestSuccess.do
  subject:
      detailUrl: https://m.duanrong.com/app/iplanDetail/borrowerInfo         #散标详情页项目详情
      fengkongUrl:  https://m.duanrong.com/newloan/fengkong     #风控信息
      investUrl:   https://m.duanrong.com/newloan/subjectTalent       #投资达人
      shareLinkUrl: https://m.duanrong.com/newloan/detail/      #投资完分享链接
      protocolUrl: http://duanrongweb.oss-cn-qingdao.aliyuncs.com/file/%E5%80%9F%E6%AC%BE%E5%8F%8A%E5%B1%85%E9%97%B4%E6%9C%8D%E5%8A%A1%E5%8D%8F%E8%AE%AE.pdf       #散标投资协议
      riskProtocolUrl: https://m.duanrong.com/html/riskInformed.html   #风险协议
      transferUrl: http://duanrongweb.oss-cn-qingdao.aliyuncs.com/file/%E5%80%BA%E6%9D%83%E8%BD%AC%E8%AE%A9%E5%8F%8A%E5%B1%85%E9%97%B4%E6%9C%8D%E5%8A%A1%E5%8D%8F%E8%AE%AE%EF%BC%8820180408%EF%BC%89.pdf   #转让协议
      transferExplainUrl: https://m.duanrong.com/html/app/transfer.html   #转让说明
      purchaseRecordUrl: https://m.duanrong.com/zqzr/transLog    #债转详情页加入记录
      creditDetailUrl: https://m.duanrong.com/app/iplan/borrowerInfo    #债权明细
      yjtTransferExplainUrl: http://m.duanrong.com/html/app/transfer-sxt.html  #转让说明
  yjt:
    picUrl: http://a.hiphotos.baidu.com/image/pic/item/500fd9f9d72a6059f550a1832334349b023bbae3.jpg
    redirectUrl: https://m.duanrong.com/html/sxt2018/index.html
  credit:
    creditIntroduceUrl: https://m.duanrong.com/html/zqzr/index.html
#日志路径
logging:
  path: /srv/soa-iPlan