spring:
  type: com.alibaba.druid.pool.DruidDataSource
  datasourceRW:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.42.171.28:3306/db_dem03
    username: demo_datarw
    password: ENC(QDWU7uDiE8Vwb8/QeBPiQt8G30+scyOZ8F63vlDhD9U=)
    max-active: 50
    initial-size: 10
    max-wait: 60000
    max-idle: 20
    min-idle: 10
    validation-query: select 1 #validationQuery是检查时用的sql语句
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    time-between-eviction-runs-millis: 60000 #隔多少时间回收废弃连接   一般比minEvictableIdleTimeMillis小
    min-evictable-idle-time-millis: 300000
  datasourceR:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.42.171.28:3306/db_dem03
    username: demo_datarw
    password: ENC(QDWU7uDiE8Vwb8/QeBPiQt8G30+scyOZ8F63vlDhD9U=)
    max-active: 50
    initial-size: 10
    max-wait: 60000
    max-idle: 20
    min-idle: 10
    validation-query: select 1 #validationQuery是检查时用的sql语句
    test-while-idle: true
    test-on-borrow: true
    test-on-return: false
    time-between-eviction-runs-millis: 60000 #隔多少时间回收废弃连接   一般比minEvictableIdleTimeMillis小
    min-evictable-idle-time-millis: 300000

server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    use-generated-keys: true

management:
  security:
    enabled: false

xm:
  enviroment:
    url: http://47.95.6.88:9000/bha-neo-app/lanmaotech/
    platformNo: 3000000186
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiU1IcqAPNwGzWA9Og9TO1bNmlETGfEgRWiqqcROvGD4VLGMabhqLdz4lV/EcengOLdU7YOKyJG5r91ghWowzYmeoFvOSxXck0sCIPO8ruPwbCRyNH0s8ijuBVsPJ60TjYW8U3VkxyjJ7AZe4SWC3ZfXhtnK25prUo7rA+xZjVcJZdN3g1V16d388ZZ++cKnJH3AK0UG43BsV+1jEoQQZ4Q98E+K9iLKXMzXwhDq8Q4PVaeBfwyiXJ4xkMiYmUpD/DCqMqkUtOiimtXXeLB0xURnsrDqxcH+AhMbPoyQ3p3EGeA7qFECK7yoDx8pcsHCxtstkzzs/ncYTho7g2K4+twIDAQAB
    privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCI2FSWnWTiS4cAhyawX2SWSI2lFUuQTBH7GXZz7wkudewGfQPd1ufh3MR7ISL+lgV4BR1YdlQh+JB78sTBA+yNclyvxXmT8jU8jaRBbUYQRjsHvZu0LFlOFLGHuDcYC4KTzaFmufCAP4+4oUFBSc+YdmREmvDLLWlxmINK9cJZO4tgwwlEEyNR6aAhtov2Y9q17nSNMHp8+Lxzg7UAOrVNH8/cmSi673KLgKVF5FsD4mG4BZLUThKyExnzNXGuR5GtR6wCidnuYKaO96Z59XRqA3XGd3RKT+K4qoiANap/uVSmvtuGE4G9OUC947EqU6KiyE9heFgw6oJpuCwZkNITAgMBAAECggEALGNPfNNtB+JL1iYArLEkpYK/P08bBaFHK9XkkFJ2/fUOLESc3nZ5HNBJg08KVN5Aw9+U1z76p1JDO5FRtPIa5v6zheheOVkVX6DqKLbTRTAisa4VNWo1RZh8xXNBm7EQF/VZZ0Lk+hSj/9V+nzjb965fc8l2VdFTJJ+95rC069BgNhhha6MwwKfH3UYC2Mru1RZTLqZWyvxM7ppTzvKT8Zqn1wHponk+He0w2UBxBzXet+AH0KMX/z7FJHW+r0g8a/45jp/ST9+Sfq2lBbVifLFUneGc3cuZ7IFAsxkEAbGAzNx9viNZ/Q2qPtduJ7CtmYHeFh6uXwW2/CdzYpA+4QKBgQD5mS2kRM/adOzDLFSfB6+8G1ZktpzDjqK0O05ZXzhkVYEfBZd4lRGpJ1I8lfPHAouinwoY/WETAvjsmosBDUN4w0PvRpu2C2RJIYKYullNp3urLIGk7oYKWl2bogwrPm7ljK6gr/60RpGGyDEVqWHzovY9m0nG9tLKT5RkAHLVawKBgQCMWtUa9Z8Xlkqs9+m3MGLccSddWzHvnHtda+2OMTObjnUUGTH+tW1BFHfVvTHxDMrirJ1a9FjFkAwhgXqwic+em4N9YVRrCZ6fGr9cFLKSfcs85Pt8LQijZ3BKrMRf75mkzp0MP4lZP42BmDo+EHT0pqoFWK6Y9jhOXs0Okh/3+QKBgB8AU5bvpRFxLGchfnEyNzWZ/6UKuXXgpXzVUOnw1cRAioUb4LBtc4AbDi/QQDMbsdRFBLAN6Jy/5cMdft5mk1bQigOSNYzq5U3gB6SIoMbwYn/kS0X9ClEG4FGQUwqb+pIwYxA6S9yAV1rySoZyP2RPfV4xh3xa89uE/t1c4OZ5AoGAfRKAbvrMX7eFKift9FnA71JCUvXuROj8Ih8IXTrJE2jaOiPNon3IM0NrGmPzeiv9LAvIWYH/DWa0+LKqQ2E7S8qnXPZ7xLqYyI2MUyD6lIJWtxgSZvC2ju6haVoV0KvyDaQ03PJNkeOJVR/zXtVJc66FOihxxks7l9LxBnf+1vkCgYEAq6Bmb2LUoRa+gZIyYBzUoHZKhVc7tjco42GjFAAsD2VNfdr1zUF/GS2s9O1UZIZ7vjqTA1jHuo8eFwPGyQiwFeUHQcSKkKgch6xJIO7pfk3sPqD/q7N690fCqEfb2hlsy5CATYCz2fKfgAiFF5LhubPhMuqte2SItUSW5gZKHpQ=
  response :
    baffle: 0 #交易挡板 挡板开关 1开启、0关闭
    time: 1 #时间挡板 挡板开关 1开启、0关闭


notice:
  url: http://dev01-soa-notify.duanrong.com
  key: duanrongf0f22ac60d07407cfb7c587f9cab
  source: iplan-service
  version: 1.0.0

drpay:
  url: http://dem03-soa-drpay.duanrong.com
  key: duanrongf0f22ac60d07407cfb7c587f9cab
  source: iplan-service
  version: 1.0.0

iPlan:
  oss:
    imagePrefix: http://drwebdemo.oss-cn-qingdao.aliyuncs.com #测试地址
  invest:
    investUserUrl: http://dem03-m.duanrong.com/iplan/talent #投资达人链接
    questionUrl: http://dem03-m.duanrong.com/html/app/lcjhQue.html  #问题链接
    shareLinkUrl: http://dem03-m.duanrong.com/iplanDetail/  #分享链接

FDD: #法大大测试配置
  FDD_APP_ID: 400170
  FDD_SECRET: FhS8QKeV9yNCmeOVlYHjUrbe
  FDD_VERSION: 2.0
  FDD_URL: https://testapi.fadada.com:8443/api/

duanrong:
  redis:
    host: 118.190.70.42
    password: duanrong123456!@#
    port: 6379
    timeout: 30000
    prefix: dem03
    config:
      maxIdle: 10
      maxTotal: 100
      minIdle: 4
      maxWaitMillis: 60000
  invest:
    shareLinkUrl: https://dem03-marketing-m.duanrong.com/weighting/profit/registe1
    tyjUrl: https://dem03-marketing-m.duanrong.com/weighting/profit/index.htm?userId=
    successUrl: http://dem03-soa-marketing.duanrong.com/web/invest/getInvestSuccess.do
  subject:
    detailUrl: https://dem03-m.duanrong.com/app/iplanDetail/borrowerInfo         #散标详情页项目详情
    fengkongUrl:  https://dem03-m.duanrong.com/newloan/fengkong     #风控信息
    investUrl:   https://dem03-m.duanrong.com/newloan/subjectTalent       #投资达人
    shareLinkUrl: https://dem03-m.duanrong.com/newloan/detail/      #投资完分享链接
    protocolUrl: https://duanrongweb.oss-cn-qingdao.aliyuncs.com/file/%E5%80%BA%E6%9D%83%E8%BD%AC%E8%AE%A9%E5%8F%8A%E5%B1%85%E9%97%B4%E6%9C%8D%E5%8A%A1%E5%8D%8F%E8%AE%AE.pdf?version=2016       #散标投资协议
    riskProtocolUrl: https://dem03-m.duanrong.com/html/riskInformed.html   #风险协议
    transferUrl: http://duanrongweb.oss-cn-qingdao.aliyuncs.com/file/%E5%80%BA%E6%9D%83%E8%BD%AC%E8%AE%A9%E5%8F%8A%E5%B1%85%E9%97%B4%E6%9C%8D%E5%8A%A1%E5%8D%8F%E8%AE%AE_New.pdf   #转让协议
    transferExplainUrl: https://dem03-m.duanrong.com/html/app/transfer.html   #转让说明
    purchaseRecordUrl: https://dem03-m.duanrong.com/zqzr/transLog    #债转详情页加入记录
    creditDetailUrl: https://dem03-m.duanrong.com/app/iplan/borrowerInfo    #债权明细
    yjtTransferExplainUrl: http://dem03-m.duanrong.com/html/app/transfer-sxt.html  #转让说明
  yjt:
    picUrl: http://a.hiphotos.baidu.com/image/pic/item/500fd9f9d72a6059f550a1832334349b023bbae3.jpg
    redirectUrl: http://m.duanrong.com/html/sxt/index.html
  credit:
      creditIntroduceUrl: https://dem03-m.duanrong.com/html/zqzr/index.html
#日志路径
logging:
  path: /srv/dem03/soa-iPlan
